# Étape 1 : Construction du build React
FROM node:18-alpine AS build

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm ci || npm ci || npm install

# Copier le reste du code
COPY . .

# ✅ Argument pour l'URL du backend
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL

RUN chmod -R 755 /app
RUN chmod +x node_modules/.bin/react-scripts


# Construire l'application React
RUN npm run build

# Étape 2 : Utiliser Nginx pour servir les fichiers
FROM nginx:alpine

# Copier le build React vers le dossier HTML de Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Configuration Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exposer le port 80
EXPOSE 80

# Lancer Nginx
CMD ["nginx", "-g", "daemon off;"]