# Étape 1 : Construction du build React
FROM node:18-alpine AS build

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm ci || npm install

# Copier le reste du code
COPY . .

# Donner les permissions correctes
RUN chmod -R 755 /app
RUN npm run build

# Étape 2 : Utiliser Nginx pour servir les fichiers
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]