version: '3.8'

services:
  smartphone-mongo:
    image: mongo:6.0
    container_name: smartphone-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - smartphone-network

  smartphone-backend:
    image: ${BACKEND_IMAGE:-votre-username/smartphone-backend:latest}
    container_name: smartphone-backend
    restart: unless-stopped
    depends_on:
      - smartphone-mongo
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://smartphone-mongo:27017/smartphone-db
    ports:
      - "5000:5000"
    networks:
      - smartphone-network

  smartphone-frontend:
    image: ${FRONTEND_IMAGE:-votre-username/smartphone-frontend:latest}
    container_name: smartphone-frontend
    restart: unless-stopped
    depends_on:
      - smartphone-backend
    ports:
      - "80:80"
    networks:
      - smartphone-network

networks:
  smartphone-network:
    driver: bridge

volumes:
  mongodb_data:
