version: '3.8'

services:
  # MongoDB Database
  smartphone-mongo:
    image: mongo:6.0
    container_name: smartphone-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: smartphone-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - smartphone-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/smartphone-db --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  smartphone-backend:
    image: ${BACKEND_IMAGE:-votre-username/smartphone-backend:latest}
    container_name: smartphone-backend
    restart: unless-stopped
    depends_on:
      smartphone-mongo:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://smartphone-mongo:27017/smartphone-db
      - FRONTEND_URL=http://localhost:80
    ports:
      - "5000:5000"
    networks:
      - smartphone-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend React
  smartphone-frontend:
    image: ${FRONTEND_IMAGE:-votre-username/smartphone-frontend:latest}
    container_name: smartphone-frontend
    restart: unless-stopped
    depends_on:
      - smartphone-backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    ports:
      - "80:80"
    networks:
      - smartphone-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  smartphone-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local