apiVersion: v1
kind: Service
metadata:
  name: smartphone-backend
  namespace: smartphone-app
  labels:
    app: smartphone-backend
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: smartphone-backend