apiVersion: v1
kind: Service
metadata:
  name: smartphone-frontend
  namespace: smartphone-app
  labels:
    app: smartphone-frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
    nodePort: 30080
  selector:
    app: smartphone-frontend