apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartphone-frontend
  namespace: smartphone-app
  labels:
    app: smartphone-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smartphone-frontend
  template:
    metadata:
      labels:
        app: smartphone-frontend
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: frontend
        image: mouhamadoumbengue/smartphone-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
        - name: REACT_APP_API_URL
          value: "http://smartphone-backend:5000/api"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
      restartPolicy: Always
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: smartphone-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smartphone-frontend
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
