apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartphone-mongo
  namespace: smartphone-app
  labels:
    app: smartphone-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartphone-mongo
  template:
    metadata:
      labels:
        app: smartphone-mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
              optional: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: smartphone-mongo
  namespace: smartphone-app
  labels:
    app: smartphone-mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
  selector:
    app: smartphone-mongo
  clusterIP: None

---