apiVersion: v1
kind: Service
metadata:
  name: smartphone-mongo
  namespace: smartphone-app
  labels:
    app: smartphone-mongo
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: http
    nodePort: 30080
  selector:
    app: smartphone-mongo