apiVersion: v1
kind: Service
metadata:
  name: smartphone-mongo
  namespace: smartphone-app
  labels:
    app: smartphone-mongo
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb
  selector:
    app: smartphone-mongo